# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://ellaxiong1.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: "/XueqianXiong"

# Title of the Site
title: Xueqian Xiong
# Description of the Site
description: An architectural/urban designer
# URL of Image of the Site
site-image: assets/images/people.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url:

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /XueqianXiong/assets/images/city.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: 1795649733@qq.com
facebook_username: thedevslot
twitter_username: thedevslot
instagram_username: thedevslot
linkedin_username: thedevslot
github_username:  Ellaxiong1
youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Xueqian Xiong
# URL for the Image of the Author
author-image: assets/images/people.jpg
# 60 Words About the Author
author-about: I am a first-year graduate student at Harbin Institute of Technology (Shenzhen), majoring in architecture with a research focus on healthy living renewal and design. My undergraduate degree is from Sichuan University.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/Ellaxiong1

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
